-- /storage/emulated/0/Documents/markor/SSP Hugo/2025/temp/Rebecca_Boyle_-_Our_Moon-Random_House_Publishing_Group_-_Random_House_(2023).sdr/metadata.epub.lua
return {
    ["annotations"] = {},
    ["config_panel_index"] = 1,
    ["copt_b_page_margin"] = 15,
    ["copt_block_rendering_mode"] = 3,
    ["copt_cjk_width_scaling"] = 100,
    ["copt_embedded_css"] = 1,
    ["copt_embedded_fonts"] = 1,
    ["copt_font_base_weight"] = 0,
    ["copt_font_gamma"] = 15,
    ["copt_font_hinting"] = 2,
    ["copt_font_kerning"] = 3,
    ["copt_font_size"] = 22,
    ["copt_h_page_margins"] = {
        [1] = 10,
        [2] = 10,
    },
    ["copt_line_spacing"] = 100,
    ["copt_nightmode_images"] = 1,
    ["copt_render_dpi"] = 96,
    ["copt_rotation_mode"] = 0,
    ["copt_smooth_scaling"] = 0,
    ["copt_status_line"] = 1,
    ["copt_sync_t_b_page_margins"] = 0,
    ["copt_t_page_margin"] = 15,
    ["copt_view_mode"] = 0,
    ["copt_visible_pages"] = 1,
    ["copt_word_expansion"] = 0,
    ["copt_word_spacing"] = {
        [1] = 95,
        [2] = 75,
    },
    ["cre_dom_version"] = 20240114,
    ["css"] = "./data/epub.css",
    ["doc_pages"] = 266,
    ["doc_path"] = "/storage/emulated/0/Documents/markor/SSP Hugo/2025/temp/Rebecca_Boyle_-_Our_Moon-Random_House_Publishing_Group_-_Random_House_(2023).epub",
    ["doc_props"] = {
        ["authors"] = "Rebecca Boyle",
        ["identifiers"] = "urn:ean:9780593129722",
        ["language"] = "en",
        ["title"] = "Our Moon",
    },
    ["floating_punctuation"] = 0,
    ["font_face"] = "Noto Serif",
    ["font_family_fonts"] = {},
    ["handmade_flows_edit_enabled"] = true,
    ["handmade_flows_enabled"] = false,
    ["handmade_toc_edit_enabled"] = true,
    ["handmade_toc_enabled"] = false,
    ["hide_nonlinear_flows"] = false,
    ["highlight_color"] = "yellow",
    ["highlight_drawer"] = "lighten",
    ["hyph_force_algorithmic"] = false,
    ["hyph_soft_hyphens_only"] = false,
    ["hyph_trust_soft_hyphens"] = false,
    ["hyphenation"] = true,
    ["inverse_reading_order"] = false,
    ["last_xpointer"] = "/body/DocFragment[1]/body/div/p/img.0",
    ["page_overlap_style"] = "dim",
    ["partial_md5_checksum"] = "be1473e28988150227e9196b7d45a6f6",
    ["partial_rerendering"] = true,
    ["preferred_dictionaries"] = {},
    ["readermenu_tab_index"] = 1,
    ["show_overlap_enable"] = false,
    ["stats"] = {
        ["authors"] = "Rebecca Boyle",
        ["highlights"] = 0,
        ["language"] = "en",
        ["notes"] = 0,
        ["pages"] = 266,
        ["performance_in_pages"] = {},
        ["series"] = "N/A",
        ["title"] = "Our Moon",
    },
    ["summary"] = {
        ["modified"] = "2025-02-02",
        ["status"] = "reading",
    },
    ["text_lang"] = "en-US",
    ["text_lang_embedded_langs"] = true,
    ["toc_ticks_ignored_levels"] = {},
}
