-- /storage/emulated/0/Documents/markor/SSP Hugo/2025/temp/Ed_Yong_-_An_Immense_World__How_Animal_Senses_Reveal_the_Hidden_Realms_Around_Us-Random_House_(2022).sdr/metadata.epub.lua
return {
    ["annotations"] = {},
    ["config_panel_index"] = 1,
    ["copt_b_page_margin"] = 15,
    ["copt_block_rendering_mode"] = 3,
    ["copt_cjk_width_scaling"] = 100,
    ["copt_embedded_css"] = 1,
    ["copt_embedded_fonts"] = 1,
    ["copt_font_base_weight"] = 0,
    ["copt_font_gamma"] = 15,
    ["copt_font_hinting"] = 2,
    ["copt_font_kerning"] = 3,
    ["copt_font_size"] = 22,
    ["copt_h_page_margins"] = {
        [1] = 10,
        [2] = 10,
    },
    ["copt_line_spacing"] = 100,
    ["copt_nightmode_images"] = 1,
    ["copt_render_dpi"] = 96,
    ["copt_rotation_mode"] = 0,
    ["copt_smooth_scaling"] = 0,
    ["copt_status_line"] = 1,
    ["copt_sync_t_b_page_margins"] = 0,
    ["copt_t_page_margin"] = 15,
    ["copt_view_mode"] = 0,
    ["copt_visible_pages"] = 1,
    ["copt_word_expansion"] = 0,
    ["copt_word_spacing"] = {
        [1] = 95,
        [2] = 75,
    },
    ["cre_dom_version"] = 20240114,
    ["css"] = "./data/epub.css",
    ["doc_pages"] = 679,
    ["doc_path"] = "/storage/emulated/0/Documents/markor/SSP Hugo/2025/temp/Ed_Yong_-_An_Immense_World__How_Animal_Senses_Reveal_the_Hidden_Realms_Around_Us-Random_House_(2022).epub",
    ["doc_props"] = {
        ["authors"] = "Yong, Ed",
        ["identifiers"] = "9780593133248",
        ["language"] = "en-US",
        ["title"] = "Immense World : How Animal Senses Reveal the Hidden Realms Around Us (9780593133248)",
    },
    ["floating_punctuation"] = 0,
    ["font_face"] = "Noto Serif",
    ["font_family_fonts"] = {},
    ["handmade_flows_edit_enabled"] = true,
    ["handmade_flows_enabled"] = false,
    ["handmade_toc_edit_enabled"] = true,
    ["handmade_toc_enabled"] = false,
    ["hide_nonlinear_flows"] = false,
    ["highlight_color"] = "yellow",
    ["highlight_drawer"] = "lighten",
    ["hyph_force_algorithmic"] = false,
    ["hyph_soft_hyphens_only"] = false,
    ["hyph_trust_soft_hyphens"] = false,
    ["hyphenation"] = true,
    ["inverse_reading_order"] = false,
    ["last_xpointer"] = "/body/DocFragment[6]/body/div[1]/p[2]/text()[2].72",
    ["page_overlap_style"] = "dim",
    ["partial_md5_checksum"] = "5ff7be2f977c2e7d4353ced284e62e6f",
    ["partial_rerendering"] = true,
    ["preferred_dictionaries"] = {},
    ["readermenu_tab_index"] = 1,
    ["show_overlap_enable"] = false,
    ["stats"] = {
        ["authors"] = "Yong, Ed",
        ["highlights"] = 0,
        ["language"] = "en-US",
        ["notes"] = 0,
        ["pages"] = 679,
        ["performance_in_pages"] = {},
        ["series"] = "N/A",
        ["title"] = "Immense World : How Animal Senses Reveal the Hidden Realms Around Us (9780593133248)",
    },
    ["summary"] = {
        ["modified"] = "2025-02-02",
        ["status"] = "reading",
    },
    ["text_lang"] = "en-US",
    ["text_lang_embedded_langs"] = true,
    ["toc_ticks_ignored_levels"] = {},
}
